- name: build postgres container...
  docker_container:
    image: postgres
    state: started
    restart: yes
    network_mode: bridge
    ports:
        -   "5432:5432"
    networks:
      - name: "{{ network_name }}"